package config

import (
	"encoding/base64"
	"testing"
)

// validKeyStr generates a valid 44-char base64-encoded 32-byte key for tests.
func validKeyStr(t *testing.T) string {
	t.Helper()
	// We can't import crypto package from tests without a full Go build,
	// so generate the key manually.
	key := make([]byte, 32)
	for i := range key {
		key[i] = byte(i)
	}
	return base64.StdEncoding.EncodeToString(key)
}

func TestLoad_AllRequiredVars(t *testing.T) {
	t.Setenv("DB_URL", "postgres://user:pass@localhost/db")
	t.Setenv("API_KEY", "my-secret-key")

	cfg, err := Load()
	if err != nil {
		t.Fatalf("Load() error: %v", err)
	}
	if cfg.DBURL != "postgres://user:pass@localhost/db" {
		t.Errorf("DBURL = %q, want %q", cfg.DBURL, "postgres://user:pass@localhost/db")
	}
	if cfg.APIKey != "my-secret-key" {
		t.Errorf("APIKey = %q, want %q", cfg.APIKey, "my-secret-key")
	}
	if cfg.Listen != ":8080" {
		t.Errorf("Listen = %q, want %q", cfg.Listen, ":8080")
	}
	if cfg.VPNContainer != "vpn" {
		t.Errorf("VPNContainer = %q, want %q", cfg.VPNContainer, "vpn")
	}
	if cfg.VPNConfigDir != "/etc/swanctl/conf.d" {
		t.Errorf("VPNConfigDir = %q, want %q", cfg.VPNConfigDir, "/etc/swanctl/conf.d")
	}
	if cfg.VPNSecretFile != "/etc/swanctl/secret" {
		t.Errorf("VPNSecretFile = %q, want %q", cfg.VPNSecretFile, "/etc/swanctl/secret")
	}
	if cfg.VPNL2TPSecretFile != "/etc/ppp/chap-secrets" {
		t.Errorf("VPNL2TPSecretFile = %q, want %q", cfg.VPNL2TPSecretFile, "/etc/ppp/chap-secrets")
	}
	if cfg.VPNLocalIP != "10.10.10.1" {
		t.Errorf("VPNLocalIP = %q, want %q", cfg.VPNLocalIP, "10.10.10.1")
	}
	if len(cfg.EncryptionKey) != 32 {
		t.Errorf("EncryptionKey length = %d, want 32", len(cfg.EncryptionKey))
	}
}

func TestLoad_MissingDBURL(t *testing.T) {
	t.Setenv("API_KEY", "my-secret-key")
	// Clear DB_URL if set
	t.Setenv("DB_URL", "")

	_, err := Load()
	if err == nil {
		t.Fatal("Load() should return error when DB_URL is missing")
	}
}

func TestLoad_MissingAPIKey(t *testing.T) {
	t.Setenv("DB_URL", "postgres://user:pass@localhost/db")
	// Clear API_KEY if set
	t.Setenv("API_KEY", "")

	_, err := Load()
	if err == nil {
		t.Fatal("Load() should return error when API_KEY is missing")
	}
}

func TestLoad_EncryptionKeySet(t *testing.T) {
	t.Setenv("DB_URL", "postgres://user:pass@localhost/db")
	t.Setenv("API_KEY", "my-secret-key")
	keyStr := validKeyStr(t)
	t.Setenv("ENCRYPTION_KEY", keyStr)

	cfg, err := Load()
	if err != nil {
		t.Fatalf("Load() error: %v", err)
	}
	if len(cfg.EncryptionKey) != 32 {
		t.Errorf("EncryptionKey length = %d, want 32", len(cfg.EncryptionKey))
	}
}

func TestLoad_EncryptionKeyAutoGenerated(t *testing.T) {
	t.Setenv("DB_URL", "postgres://user:pass@localhost/db")
	t.Setenv("API_KEY", "my-secret-key")
	// Don't set ENCRYPTION_KEY — should be auto-generated
	t.Setenv("ENCRYPTION_KEY", "")

	cfg, err := Load()
	if err != nil {
		t.Fatalf("Load() error: %v", err)
	}
	if cfg.EncryptionKey == nil {
		t.Error("EncryptionKey should be non-nil when auto-generated")
	}
	if len(cfg.EncryptionKey) != 32 {
		t.Errorf("EncryptionKey length = %d, want 32", len(cfg.EncryptionKey))
	}
}

func TestLoad_EncryptionKeyInvalidBase64(t *testing.T) {
	t.Setenv("DB_URL", "postgres://user:pass@localhost/db")
	t.Setenv("API_KEY", "my-secret-key")
	t.Setenv("ENCRYPTION_KEY", "not-valid-base64!!!")

	_, err := Load()
	if err == nil {
		t.Fatal("Load() should return error for invalid ENCRYPTION_KEY base64")
	}
}

func TestLoad_CustomOverrides(t *testing.T) {
	t.Setenv("DB_URL", "postgres://user:pass@localhost/db")
	t.Setenv("API_KEY", "my-secret-key")
	t.Setenv("LISTEN", ":9090")
	t.Setenv("VPN_CONTAINER", "my-vpn-container")
	t.Setenv("VPN_CONFIG_DIR", "/custom/conf.d")
	t.Setenv("VPN_SECRET_FILE", "/custom/secret")
	t.Setenv("VPN_L2TP_SECRET_FILE", "/custom/chap-secrets")
	t.Setenv("VPN_LOCAL_IP", "10.20.30.1")

	cfg, err := Load()
	if err != nil {
		t.Fatalf("Load() error: %v", err)
	}
	if cfg.Listen != ":9090" {
		t.Errorf("Listen = %q, want %q", cfg.Listen, ":9090")
	}
	if cfg.VPNContainer != "my-vpn-container" {
		t.Errorf("VPNContainer = %q, want %q", cfg.VPNContainer, "my-vpn-container")
	}
	if cfg.VPNConfigDir != "/custom/conf.d" {
		t.Errorf("VPNConfigDir = %q, want %q", cfg.VPNConfigDir, "/custom/conf.d")
	}
	if cfg.VPNSecretFile != "/custom/secret" {
		t.Errorf("VPNSecretFile = %q, want %q", cfg.VPNSecretFile, "/custom/secret")
	}
	if cfg.VPNL2TPSecretFile != "/custom/chap-secrets" {
		t.Errorf("VPNL2TPSecretFile = %q, want %q", cfg.VPNL2TPSecretFile, "/custom/chap-secrets")
	}
	if cfg.VPNLocalIP != "10.20.30.1" {
		t.Errorf("VPNLocalIP = %q, want %q", cfg.VPNLocalIP, "10.20.30.1")
	}
}

func TestLoad_VPNLocalIPDefault(t *testing.T) {
	t.Setenv("DB_URL", "postgres://user:pass@localhost/db")
	t.Setenv("API_KEY", "my-secret-key")
	// Explicitly clear VPN_LOCAL_IP
	t.Setenv("VPN_LOCAL_IP", "")

	cfg, err := Load()
	if err != nil {
		t.Fatalf("Load() error: %v", err)
	}
	if cfg.VPNLocalIP != "10.10.10.1" {
		t.Errorf("VPNLocalIP = %q, want default %q", cfg.VPNLocalIP, "10.10.10.1")
	}
}

func TestLoad_VPNLocalIPCustom(t *testing.T) {
	t.Setenv("DB_URL", "postgres://user:pass@localhost/db")
	t.Setenv("API_KEY", "my-secret-key")
	t.Setenv("VPN_LOCAL_IP", "172.16.0.1")

	cfg, err := Load()
	if err != nil {
		t.Fatalf("Load() error: %v", err)
	}
	if cfg.VPNLocalIP != "172.16.0.1" {
		t.Errorf("VPNLocalIP = %q, want %q", cfg.VPNLocalIP, "172.16.0.1")
	}
}
