# strongSwan daemon configuration
# Minimal config — no includes, no extra plugins.

charon {
    load_modular = no
    plugins {
        load = aes sha1 sha256 sha384 sha512 random nonce hmac mgf1 pubkey pkcs1 x509 kernel-netlink socket-default updown vici
    }

    filelog {
        stdout {
            time_format = %Y-%m-%dT%H:%M:%S
            ike_name = yes
            append = no
            default = 4
        }
    }
}
