[global]
listen-addr = 0.0.0.0
auth file = /etc/ppp/chap-secrets

[lns default]
exclusive = yes
ip range = ${VPN_POOL_RANGE:-10.10.10.2-10.10.10.254}
local ip = ${VPN_POOL_LOCAL_IP:-10.10.10.1}
refuse pap = yes
refuse chap = no
require chap = yes
require authentication = yes
name = l2tp-vpn
pppoptfile = /etc/ppp/options.xl2tpd
